name: Build UI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
        include:
          - os: ubuntu-latest
            command: |
                sudo apt-get update && sudo apt install libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev libsoup2.4-dev libudev-dev
                cd host/ui
                cargo build --verbose --release
            binary: host/target/release/ui
          - os: windows-2019
            command: |
                cd host\ui
                cargo build --verbose --release
            binary: host\target\release\ui.exe

    steps:
      - name: Release build
        uses: actions/checkout@v3
      - run: |
          ${{ matrix.command }}
      - name: Archive release build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ matrix.binary }}
